# Generated by Django 4.0.6 on 2022-09-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_incentivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[(0, 'etiquetado'), (1, 'clasificado')], max_length=45)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_archivo', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('etiqueta', models.JSONField()),
                ('caneca', models.CharField(choices=[(0, 'Ordinario'), (1, 'Papel_Carton'), (2, 'Plastico'), (3, 'Vidrio'), (4, 'Organicos'), (5, 'Residuos_Peligrosos'), (6, 'Aluminio')], max_length=45)),
                ('fecha_etiquetado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_puntos', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_residuo', models.PositiveIntegerField()),
                ('Etiqueta_id_archivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Canecas',
        ),
        migrations.DeleteModel(
            name='Incentivos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='puntos',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='Usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.usuario'),
        ),
    ]
