# Generated by Django 4.0.6 on 2022-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_puntos_fecha_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(choices=[('etiquetado', 'etiquetado'), ('clasificado', 'clasificado')], max_length=45),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='caneca',
            field=models.CharField(choices=[('Ordinario', 'Ordinario'), ('Papel_Carton', 'Papel_Carton'), ('Plastico', 'Plastico'), ('Vidrio', 'Vidrio'), ('Organicos', 'Organicos'), ('Residuos_Peligrosos', 'Residuos_Peligrosos'), ('Aluminio', 'Aluminio')], max_length=45),
        ),
    ]
