# Generated by Django 4.0.6 on 2022-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_actividad_tipo_actividad_alter_etiqueta_caneca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='id_archivo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
